version: '3.1'
services:
  app:
    working_dir: /app
    build: 
      context: .
      dockerfile: Dockerfile
      target: production
    environment:
      - NODE_ENV=production
    # ports:
    #   - "3000:3000"

  nginx:
    container_name: nginx
    image: nginx:1.25.3
    ports:
      - "3000:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app